txlege84/txlege84/urls.py
from django.conf.urls import patterns, include, url
# from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.contrib import admin

from bills.views import (BillDetail, BillSearchView, BillSearchJson,
                         SubjectDetail, SubjectListDetail, LegeStreamDetail,
                         NewLawsListDetail, VetoedListDetail)

from core.views import LandingView
from committees.views import (ChamberCommitteeList,
                              CommitteeDetail, CommitteeList)
from explainers.views import ExplainerDetail, ExplainerListDetail
from legislators.views import LegislatorDetail, LegislatorList
from topics.views import IssueDetail, TopicDetail

urlpatterns = patterns(
    '',

    # Landing page
    url(r'^$', LandingView.as_view(), name='landing-view'),

    # Topic pages
    url(r'^topics/(?P<hot_list_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        IssueDetail.as_view(), name='issue-detail'),
    url(r'^topics/(?P<slug>[-\w]+)/$',
        TopicDetail.as_view(), name='topic-detail'),
    url(r'^topics/$',
        RedirectView.as_view(pattern_name='landing-view')),

    # Bill pages
    url(r'^84/bills/new-laws/$',
        NewLawsListDetail.as_view(), name='new-laws'),
    url(r'^84/bills/vetoed/$',
        VetoedListDetail.as_view(), name='vetoed-bills'),
    url(r'^84/bills/(?P<slug>[-\w]+)/$',
        BillDetail.as_view(), name='bill-detail'),
    url(r'^84/bills/$', BillSearchView.as_view(), name='find-bills'),

    # Subject pages
    url(r'^84/categories/(?P<slug>[-\w]+)/$',
        SubjectDetail.as_view(), name='category-detail'),
    url(r'^84/categories/$',
        SubjectListDetail.as_view(), name='category-list-detail'),

    # Legislator pages
    url(r'^84/legislators/(?P<slug>[-\w]+)/$',
        LegislatorDetail.as_view(), name='legislator-detail'),
    url(r'^84/legislators/$',
        LegislatorList.as_view(), name='legislator-landing'),

    # Committee pages
    url(r'^84/committees/(?P<chamber>[-\w]+)/(?P<slug>[-\w]+)/$',
        CommitteeDetail.as_view(), name='committee-detail'),
    url(r'^84/committees/(?P<slug>[-\w]+)/$',
        ChamberCommitteeList.as_view(), name='chamber-committees'),
    url(r'^84/committees/$',
        CommitteeList.as_view(), name='committees-landing'),

    # Explainer pages
    url(r'^how-session-works/$',
        ExplainerListDetail.as_view(), name='explainer-list-detail'),
    url(r'^how-session-works/(?P<slug>[-\w]+)/$',
        ExplainerDetail.as_view(), name='explainer-detail'),

    # Livestream pages
    url(r'^livestream/$',
        LegeStreamDetail.as_view(), name='legestream'),

    # JSON feed for bill search
    url(r'^search/bills/', BillSearchJson.as_view(), name='bill-search'),

    # Redirects
    url(r'^hot-lists/$',
        RedirectView.as_view(pattern_name='landing-view')),
    url(r'^hot-lists/(?P<slug>[-\w]+)/$',
        RedirectView.as_view(pattern_name='topic-detail')),
    url(r'^hot-lists/(?P<hot_list_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        RedirectView.as_view(pattern_name='issue-detail')),
    url(r'^legestream/$', RedirectView.as_view(pattern_name='legestream')),
    url(r'^texplainers/$',
        RedirectView.as_view(pattern_name='explainer-list-detail')),

    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the import above and next line to serve media files in development
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

txlege84/bills/models.py
from django.db import models
from django.utils.text import slugify

from committees.models import Committee
from legislators.models import Chamber, Legislator


BILL_TYPES = {
    'HB': 'House Bill',
    'SB': 'Senate Bill',
    'HR': 'House Resolution',
    'SR': 'Senate Resolution',
    'HJR': 'House Joint Resolution',
    'SJR': 'Senate Joint Resolution',
    'HCR': 'House Concurrent Resolution',
    'SCR': 'Senate Concurrent Resolution',
}


class Subject(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)[:50]

        super(Subject, self).save(*args, **kwargs)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('category-detail', args=(self.slug,))


class Bill(models.Model):
    name = models.CharField(max_length=10)
    bill_number = models.IntegerField(null=True, blank=True)
    description = models.TextField()
    chamber = models.ForeignKey(Chamber, related_name='bills')
    sponsors = models.ManyToManyField(Legislator, through='Sponsorship')
    subjects = models.ManyToManyField(Subject, related_name='bills')
    openstates_id = models.CharField(max_length=11, unique=True)
    bill_type = models.CharField(max_length=21)
    slug = models.SlugField()

    first_action_date = models.DateField(null=True, blank=True)
    last_action_date = models.DateField(null=True, blank=True)
    passed_senate = models.DateField(null=True, blank=True)
    passed_house = models.DateField(null=True, blank=True)
    became_law = models.DateField(null=True, blank=True)
    vetoed = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('chamber__name', 'bill_type', 'bill_number',)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = self.name.replace(' ', '')

        super(Bill, self).save(*args, **kwargs)

    @property
    def house_committee(self):
        try:
            return self.actions.reverse().exclude(
                related_committee__isnull=True).filter(
                acting_chamber__name='Texas House')[0].related_committee
        except IndexError:
            return None

    @property
    def senate_committee(self):
        try:
            return self.actions.reverse().exclude(
                related_committee__isnull=True).filter(
                acting_chamber__name='Texas Senate')[0].related_committee
        except IndexError:
            return None

    @property
    def long_name(self):
        split_name = self.name.split(' ')

        return '{0} {1}'.format(
            BILL_TYPES[split_name[0]], split_name[1])

    @property
    def authors(self):
        return self.sponsorships.filter(role='author')

    @property
    def coauthors(self):
        return self.sponsorships.filter(role='coauthor')

    @property
    def sponsors(self):
        return self.sponsorships.filter(role='sponsor')

    @property
    def cosponsors(self):
        return self.sponsorships.filter(role='cosponsor')

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('bill-detail', args=(self.slug,))


class Action(models.Model):
    number = models.CharField(max_length=4)
    text = models.CharField(max_length=100)
    date = models.DateField()
    acting_chamber = models.ForeignKey(Chamber, related_name='actions')
    related_committee = models.ForeignKey(
        Committee, related_name='actions', null=True, blank=True)
    bill = models.ForeignKey(Bill, related_name='actions')

    class Meta:
        ordering = ['date', 'pk']


class Sponsorship(models.Model):
    legislator = models.ForeignKey(Legislator, related_name='sponsorships')
    bill = models.ForeignKey(Bill, related_name='sponsorships')
    role = models.CharField(max_length=20)
    ordering = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return u'{0} as {1} of {2}'.format(
            self.legislator.full_name, self.role, self.bill)

    class Meta:
        ordering = ['ordering']

txlege84/committees/models.py
from django.db import models
from django.utils.text import slugify

from legislators.models import Chamber, Legislator


class Committee(models.Model):
    name = models.CharField(max_length=60)
    chamber = models.ForeignKey(Chamber, related_name='committees')
    openstates_id = models.CharField(max_length=9, unique=True)
    members = models.ManyToManyField(Legislator, through='Membership')
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)[:50]

        super(Committee, self).save(*args, **kwargs)

    @property
    def chair(self):
        return self.memberships.get(role='Chair').legislator

    @property
    def vice_chair(self):
        return self.memberships.get(role='Vice Chair').legislator

    @property
    def member_list(self):
        return self.memberships.filter(role='Member').order_by('legislator__last_name')

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('committee-detail', args=(
            self.chamber.slug, self.slug,))


class Membership(models.Model):
    legislator = models.ForeignKey(Legislator, related_name='memberships')
    committee = models.ForeignKey(Committee, related_name='memberships')
    role = models.CharField(max_length=20)

    def __unicode__(self):
        return '{0} in {1}'.format(self.role, self.committee.name)


class Event(models.Model):
    pass

txlege84/explainers/models.py
from django.db import models
from django.utils.text import slugify

from txlege84.managers import PublishedQuerySet

PUBLICATION_CHOICES = (
    (u'D', u'Draft'),
    (u'P', u'Published'),
    (u'W', u'Withdrawn'),
)


class Explainer(models.Model):
    name = models.CharField(u'title', max_length=200)
    youtube_id = models.CharField(u'YouTube ID', max_length=11)
    text = models.TextField()
    order = models.PositiveIntegerField(default=0)
    slug = models.SlugField()
    status = models.CharField(
        max_length=1, choices=PUBLICATION_CHOICES, default=u'D')

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    objects = PublishedQuerySet.as_manager()

    class Meta:
        ordering = ('order',)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)[:50]

        super(Explainer, self).save(*args, **kwargs)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('explainer-detail', args=(self.slug,))

txlege84/bills/views.py
from django.http import JsonResponse
from django.views.generic import DetailView, ListView, TemplateView

from bills.mixins import AllSubjectsMixin
from core.mixins import ConveneTimeMixin
from committees.mixins import AllCommitteesMixin
from legislators.mixins import AllLegislatorsMixin, ChambersMixin
from bills.models import Bill, Subject


class BillDetail(AllSubjectsMixin, AllLegislatorsMixin,
                 ConveneTimeMixin, DetailView):
    model = Bill
    template_name = 'pages/bill.html'


class NewLawsListDetail(AllSubjectsMixin, AllLegislatorsMixin,
                        ConveneTimeMixin, ListView):
    queryset = Bill.objects.filter(became_law__isnull=False)
    template_name = 'pages/new-laws.html'


class VetoedListDetail(AllSubjectsMixin, AllLegislatorsMixin,
                       ConveneTimeMixin, ListView):
    queryset = Bill.objects.filter(vetoed__isnull=False)
    template_name = 'pages/vetoed-bills.html'


class SubjectDetail(AllSubjectsMixin, AllLegislatorsMixin,
                    ConveneTimeMixin, DetailView):
    model = Subject
    template_name = 'pages/subject.html'


class SubjectListDetail(ConveneTimeMixin, ListView):
    model = Subject
    template_name = 'pages/subject-list.html'


class BillSearchView(AllLegislatorsMixin, AllSubjectsMixin,
                     AllCommitteesMixin, ConveneTimeMixin, TemplateView):
    template_name = 'pages/find-bills.html'


class BillSearchJson(ListView):
    queryset = Bill.objects.all().values('name', 'slug')

    def render_to_response(self, context, **kwargs):
        return JsonResponse(list(context['object_list']), safe=False)


class LegeStreamDetail(AllSubjectsMixin, AllLegislatorsMixin,
                       ChambersMixin, ConveneTimeMixin, TemplateView):
    template_name = 'pages/legestream.html'

txlege84/committees/views.py
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, ListView

from bills.mixins import AllSubjectsMixin
from core.mixins import ConveneTimeMixin
from legislators.mixins import AllLegislatorsMixin

from committees.models import Committee
from legislators.models import Chamber


class CommitteeList(ConveneTimeMixin, ListView):
    model = Committee
    template_name = 'pages/committees-landing.html'


class ChamberCommitteeList(ConveneTimeMixin, DetailView):
    model = Chamber
    template_name = 'pages/chamber-committees.html'


class CommitteeDetail(AllSubjectsMixin, AllLegislatorsMixin,
                      ConveneTimeMixin, DetailView):
    model = Committee
    template_name = 'pages/committee.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        chamber_slug = self.kwargs.get('chamber', None)
        slug = self.kwargs.get(self.slug_url_kwarg, None)

        if slug is not None and chamber_slug is not None:
            chamber_field = 'chamber__slug'
            slug_field = self.get_slug_field()
            queryset = queryset.filter(
                **{slug_field: slug, chamber_field: chamber_slug})

        # If none of those are defined, it's an error.
        else:
            raise AttributeError("Generic detail view %s must be called with "
                                 "both a chamber_slug and a slug."
                                 % self.__class__.__name__)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj

txlege84/explainers/views.py
from django.views.generic import DetailView, ListView

from core.mixins import ConveneTimeMixin

from explainers.models import Explainer


class ExplainerListDetail(ConveneTimeMixin, ListView):
    queryset = Explainer.objects.all().published()
    template_name = 'pages/explainer-landing.html'


class ExplainerDetail(ConveneTimeMixin, DetailView):
    model = Explainer
    template_name = 'pages/explainer.html'

txlege84/legislators/views.py
from django.views.generic import DetailView, ListView

from bills.mixins import AllSubjectsMixin
from core.mixins import ConveneTimeMixin
from legislators.mixins import AllLegislatorsMixin
from legislators.models import Legislator


class LegislatorList(AllLegislatorsMixin, ConveneTimeMixin, ListView):
    model = Legislator
    template_name = 'pages/legislator-landing.html'


class LegislatorDetail(AllSubjectsMixin, AllLegislatorsMixin,
                       ConveneTimeMixin, DetailView):
    model = Legislator
    template_name = 'pages/legislator.html'

txlege84/templates/pages/committee-landing.html
{% extends 'base.html' %}

{% block og_data %}
  {% include "includes/og/og_issue.html" %}
{% endblock %}

{% block content %}
{% load staticfiles %}

<section>
  <h5 class="section-header">Browse Committees</h5>

  <section class="share-page">
    <ul>
      <a href="mailto:?subject=}&body=">
        <li class="email"><i class="fa fa-envelope"></i></li>
      </a>
      <a href="https://twitter.com/intent/tweet?text=&via=texastribune" title="share on Twitter" class="social-share" target="_blank">
        <li class="facebook"><i class="fa fa-twitter"></i></li>
      </a>
      <a href="https://www.facebook.com/dialog/share?app_id=154122474650943&display=popup&href=TK&redirect_uri=http%3A%2F%2Ftxlege.texastribune.org" title="share on Facebook" class="social-share" target="_blank">
        <li class="twitter"><i class="fa fa-facebook"></i></li>
      </a>
    </ul>
  </section>

  <div class="shutter">
    <div class="shutter-label">
      House Committees
      <span class="icon closed">&#43;</span>
      <span class="icon open">&#45;</span>
    </div>
    <ul class="sans">
      {% for committee in committee_list %}
        {% if committee.chamber.name == "Texas House" %}
        <li><a href="{{ committee.get_absolute.url }}">{{ committee.name }}</a></li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>

  <div class="shutter">
    <div class="shutter-label">
      Senate Committees
      <span class="icon closed">&#43;</span>
      <span class="icon open">&#45;</span>
    </div>
      <ul class="sans">
      {% for committee in committee_list %}
        {% if committee.chamber.name == "Texas Senate" %}
        <li><a href="{{ committee.get_absolute.url }}">{{ committee.name }}</a></li>
        {% endif %}
      {% endfor %}
      </ul>
  </div>

<!--   <div class="shutter">
    <div class="shutter-label">
      Joint Committees
      <span class="icon closed">&#43;</span>
      <span class="icon open">&#45;</span>
    </div>
  </div> -->

</section>



{% endblock %}

txlege84/templates/pages/find-bills.html
{% extends 'base.html' %}

{% block og_data %}
  {% include "includes/og/og_bill.html" %}
{% endblock %}

{% load staticfiles %}
{% block content %}
<section>
  <header class="page-header">
    <h2>Find bills</h2>
    <p class="sub-text">Look up legislation by number, such as SB 1 or HR 200. You can also browse bills by category, lawmaker or committee by clicking on the links below.</p>
    <div class="bill-search">
      <i class="fa fa-search"></i>
      <form>
        <input class="bill-search-form" id="bill-search" type="text" placeholder="E.g. HB 200, SR 124">
      </form>
    </div>
  </header>
  <div class="share-page">
    <ul>
      <a href="mailto:?subject=The%20Texas%20Tribune%27s%20Texas%20Legislative%20Guide%3A%20Bill%20Finder&body=I%20found%20a%20handy%20tool%20for%20finding%20bills%20in%20the%20current%20Texas%20Legislature.%20Browse%20by%20lawmaker%2C%20committee%20or%20bill%20number%20using%20The%20Texas%20Tribune%27s%20Texas%20Legislative%20Guide.%0A%0Ahttp%3A%2F%2Ftxlege.texastribune.org{% url 'find-bills' %}">
        <li class="email"><i class="fa fa-envelope"></i></li>
      </a>
      <a href="https://twitter.com/intent/tweet?text=&via=texastribune" title="share on Twitter" class="social-share" target="_blank">
        <li class="twitter"><i class="fa fa-twitter"></i></li>
      </a>
      <a href="https://www.facebook.com/dialog/share?app_id=154122474650943&display=popup&href=TK&redirect_uri=http%3A%2F%2Ftxlege.texastribune.org" title="share on Facebook" class="social-share" target="_blank">
        <li class="facebook"><i class="fa fa-facebook"></i></li>
      </a>
    </ul>
  </div>
</section>

{% include "includes/banner_ad.html" %}
<section>
    <div class="shutter">
      <div class="shutter-label">
        Browse Bills by Category
        <span class="shutter-icon"></span>
      </div>
      <div class="shutter-content">
        <ul class="sans find-bill-list">
        {% for category in subject_list %}
          <li> <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="shutter">
      <div class="shutter-label">
        Browse Bills by Senator
        <span class="shutter-icon"></span>
      </div>
      <div class="shutter-content">
        <ul class="sans find-bill-list">
        {% for legislator in sen_list %}
          <li><a href="{{ legislator.get_absolute_url }}">{{ legislator.last_first_full_name }} <span class="{{ legislator.party.name|lower }}">({{ legislator.party.short_name }})</span></a></li>
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="shutter">
      <div class="shutter-label">
        Browse Bills by Representative
        <span class="shutter-icon"></span>
      </div>
      <div class="shutter-content">
        <ul class="sans find-bill-list">
        {% for legislator in rep_list %}
          <li><a href="{{ legislator.get_absolute_url }}">{{ legislator.last_first_full_name }} <span class="{{ legislator.party.name|lower }}">({{ legislator.party.short_name }})</span></a></li>
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="shutter">
      <div class="shutter-label">
        Browse Bills by Senate Committee
        <span class="shutter-icon"></span>
      </div>
      <div class="shutter-content">
        <ul class="sans find-bill-list">
        {% for committee in committee_list %}
          {% if committee.chamber.name == 'Texas Senate' %}
          <li> <a href="{{ committee.get_absolute_url }}">{{ committee.name }}</a></li>
          {% endif %}
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="shutter">
      <div class="shutter-label">
        Browse Bills by House Committee
        <span class="shutter-icon"></span>
      </div>
      <div class="shutter-content">
        <ul class="sans find-bill-list">
        {% for committee in committee_list %}
          {% if committee.chamber.name == 'Texas House' %}
          <li> <a href="{{ committee.get_absolute_url }}">{{ committee.name }}</a></li>
          {% endif %}
        {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
</section>
  <section class="newsletter-signup">
    <header>
      <h4 class="sub-section-header">Sign up for The Brief: The news you need to start your day.</h4>
    </header>
    <!-- Begin MailChimp Signup Form -->
    <div id="mc_embed_signup">
      <form action="//texastribune.us3.list-manage2.com/subscribe/post?u=3d0ce87edeeb6df90043897db&amp;id=68501b81bf" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
      <div class="mc-field-group">
        <label class="hidden" for="mce-EMAIL"></label>
        <input class="required input_neue" type="email" name="EMAIL" value="" placeholder="username@email.com" />
        <input class="button" type="submit" name="subscribe" value="Subscribe" />
      </div>
        <div id="mce-responses" class="clear">
          <div class="response" id="mce-error-response" style="display:none"></div>
          <div class="response" id="mce-success-response" style="display:none"></div>
        </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;">
            <input type="text" name="b_3d0ce87edeeb6df90043897db_7476115edd" tabindex="-1" value=""></div>
          </div>
      </form>
    </div>
    <!-- https://us3.admin.mailchimp.com/lists/integration/embeddedcode?id=271841 -->
    <!--End mc_embed_signup-->
  </section>
{% endblock %}

txlege84/templates/pages/subject-list.html
{% extends 'base.html' %}

{% block og_data %}
  {% include "includes/og/og_bill.html" %}
{% endblock %}

{% load staticfiles %}
{% block content %}

<section>
  <header class="page-header">
  <h2>Bill categories</h2>
  <p class="sub-text">Bills are categorized by <a href="http://openstates.org/">Open States</a>, a product of the Sunlight Foundation.</p>
  </header>
  <div class="share-page">
    <ul>
      <a href="mailto:?subject=The%20Texas%20Tribune%27s%20Texas%20Legislative%20Guide&body=I%20thought%20you%20might%20be%20interested%20in%20learning%20more%20about%20the%20Texas%20Legislature.%20Check%20out%20this%20list%20of%20bill%20categories%20to%20find%20the%20legislation%20related%20to%20your%20interests.%20%20%0D%0Dhttp%3A%2F%2Ftxlege.texastribune.org{% url 'category-list-detail' %}">
        <li class="email"><i class="fa fa-envelope"></i></li>
      </a>
      <a href="https://twitter.com/intent/tweet?text=&via=texastribune" title="share on Twitter" class="social-share" target="_blank">
        <li class="twitter"><i class="fa fa-twitter"></i></li>
      </a>
      <a href="https://www.facebook.com/dialog/share?app_id=154122474650943&display=popup&href=http%3A%2F%2Ftxlege.texastribune.org&redirect_uri=http%3A%2F%2Ftxlege.texastribune.org" title="share on Facebook" class="social-share" target="_blank">
        <li class="facebook"><i class="fa fa-facebook"></i></li>
      </a>
    </ul>
  </div>
</section>

  {% include "includes/banner_ad.html" %}

<section>
  <ul class="sans">
  {% for subject in subject_list %}
    <li><a href="{{ subject.get_absolute_url }}">{{ subject.name }}</a></li>
  {% endfor %}
  </ul>
</section>

{% endblock %}

txlege84/templates/pages/vetoed-bills.html
{% extends 'base.html' %}

{% block og_data %}
  {% include "includes/og/og_bill.html" %}
{% endblock %}

{% load staticfiles %}
{% block content %}

<section>
  <header class="page-header">
  <h2>Vetoed Bills</h2>
  <p class="sub-text">Below is a list of bills that Gov. Greg Abbott has vetoed. The governor has until June 21, 2015 to veto bills approved by both chambers in the 84th legislative session. After that date, bills automatically become law. <a href="{% url 'new-laws' %}">See a list of bills that became new laws</a>.</p>
  </header>
  <div class="share-page">
    <ul>
      <a href="mailto:?subject=The%20Texas%20Tribune%27s%20Texas%20Legislative%20Guide&body=Check%20out%20this%20list%20of%20vetoed%20bills%20from%20Texas%E2%80%99%2084th%20legislative%20session%2C%20courtesy%20of%20The%20Texas%20Tribune%27s%20Texas%20Legislative%20Guide.%20%20%0D%0Dhttp%3A%2F%2Ftxlege.texastribune.org{% url 'vetoed-bills' %}">
        <li class="email"><i class="fa fa-envelope"></i></li>
      </a>
      <a href="https://twitter.com/intent/tweet?text=&via=texastribune" title="share on Twitter" class="social-share" target="_blank">
        <li class="twitter"><i class="fa fa-twitter"></i></li>
      </a>
      <a href="https://www.facebook.com/dialog/share?app_id=154122474650943&display=popup&href=http%3A%2F%2Ftxlege.texastribune.org&redirect_uri=http%3A%2F%2Ftxlege.texastribune.org" title="share on Facebook" class="social-share" target="_blank">
        <li class="facebook"><i class="fa fa-facebook"></i></li>
      </a>
    </ul>
  </div>
</section>

  {% include "includes/banner_ad.html" %}

<section>
  <div>
    <table>
      <thead>
        <tr>
          <th>Bill</th>
          <th class="align-left">Description</th>
          <th>Date of Veto</th>
        </tr>
      </thead>
      <tbody>
      {% for bill in bill_list %}
        <tr>
          <td data-title="Bill"><a href="{{ bill.get_absolute_url }}">{{ bill.name }}</a></td>
          <td class="align-left" data-title="Description">{{ bill.description }}</td>
          <td data-title="Date of Veto">{{ bill.actions.last.date|date:"SHORT_DATE_FORMAT" }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</section>

{% endblock %}